default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: dev
  password: dev            # set this to your actual dev password if it's different
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: wordless_spy_development

test:
  <<: *default
  database: wordless_spy_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>